feat: added postgres-redis subscription, updated dockerfiles

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,17 +1,26 @@
-# Build stage
-FROM node:20-alpine AS build
-WORKDIR /app
-
-RUN npm install -g pnpm
-
-COPY . .
-RUN pnpm install
-RUN pnpm build
-
-# Run stage
+# Base image
 FROM node:20-alpine
+
+# It's important to update the index before installing packages to ensure you're getting the latest versions.
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk update && apk upgrade --no-cache libcrypto3 libssl3 libc6-compat
+
 WORKDIR /app
-RUN npm install -g pnpm
-COPY --from=build /app /app
-COPY --from=build /app/node_modules /app/node_modules
-CMD ["pnpm", "start"]
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Copy the rest of the application source code
+COPY . .
+
+# Build your application if necessary
+RUN npm run build
+
+# Run application
+CMD ["npm", "start"]
